### ISSUE TITLE
Add support for more source parts syntax

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/snapcraft-poller-script#50]
My parts point at tags, not branches.

The poller doesn't seem to have support for this, and seems to trigger rebuilds of my snap every 2 days, whilst none of the parts sources have changed.

This is happening at a significant compute & emissions cost.

I'll try to work on improving this.

**Comment by xnox** [comment]
Fixed in https://github.com/canonical/snapcraft-poller-script/pull/51

**Comment by xnox** [comment]
@Lukewh has #51 made it into production build of this service container and deployed? I still see my snap pointlessly triggered for rebuilds.

**Comment by Lukewh** [comment]
@xnox should have been deployed and working as of a few minutes ago :)

**Comment by xnox** [comment]
@Lukewh horay! finally docker snap stopped getting rebuilt every two days.

It would be interesting to know (maybe privately) if the stats have any significant drop, i.e. two days before & two days after deploy, if the average number of triggered snaps got lower.
